routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Controllers
use App\Http\Controllers\AboutController;
use App\Http\Controllers\AddictionController;
use App\Http\Controllers\AffirmationsController;
use App\Http\Controllers\BucketListController;
use App\Http\Controllers\FeatureVoteController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\HabitsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PushController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\ToDoController;
use App\Http\Controllers\TutorialsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes(['verify' => true]);

// Root route, controls whether or not user gets sent to about or home
Route::get('/', [HomeController::class, 'index'])->name('root');

// Main about page
Route::get('about', [AboutController::class, 'index'])->name('about');

// Privacy policy/tos
Route::get('privacy', [AboutController::class, 'privacy'])->name('privacy');
Route::get('tos', [AboutController::class, 'tos'])->name('tos');

// FAQ
Route::get('faqs', [AboutController::class, 'faqs'])->name('faqs');

// Tutorials
Route::get('tutorials', [TutorialsController::class, 'index'])->name('tutorials');

// Referal sign up link
Route::get('refer/{slug}', [HomeController::class, 'refer']);

// Web push store subscribtion
Route::post('push', [PushController::class, 'store']);

// Home route
Route::group(['prefix' => 'home', 'middleware' => ['auth', 'verified']], function(){
    // View tools page
    Route::get('/', [HomeController::class, 'home'])->name('home');

    // Edit/update routes
    Route::get('edit', [HomeController::class, 'edit'])->name('home.edit');
    Route::post('hide/{home}', [HomeController::class, 'hide'])->name('home.hide');
    Route::post('show/{home}', [HomeController::class, 'show'])->name('home.show');
});

// Journal
Route::prefix('journal')->group(function(){
    // Root
    Route::get('/', [JournalController::class, 'index'])->name('journal');

    // View the journal mood colors guide
    Route::get('colors', [JournalController::class, 'colorGuide'])->name('journal.colors');

    // Views
    Route::prefix('view')->group(function(){
        // List view
        Route::get('list/{month?}/{year?}', [JournalController::class, 'viewList'])->name('journal.view.list')
            ->where('month', config('regex.month_name'))
            ->where('year', config('regex.year'));

        // Day view
        Route::get('day/{date}', [JournalController::class, 'viewDay'])->name('journal.view.day')
            ->where('date', config('regex.route_date'));

        // Entry view
        Route::get('entry/{journal_entry}', [JournalController::class, 'viewEntry'])->name('journal.view.entry');

        // ToDo view
        Route::get('todo/{todo}', [JournalController::class, 'viewToDo'])->name('journal.view.todo');
    });

    // Search functionality
    Route::get('search', [JournalController::class, 'search'])->name('journal.search');

    // Create Entry
    Route::get('create/entry', [JournalController::class, 'createEntry'])->name('journal.create.entry');

    // Store routes
    Route::prefix('store')->group(function(){
        Route::post('category', [JournalController::class, 'storeCategory'])->name('journal.store.category');
        Route::post('entry', [JournalController::class, 'storeEntry'])->name('journal.store.entry');
    });

    // Edit routes
    Route::prefix('edit')->group(function(){
        Route::get('categories', [JournalController::class, 'editCategories'])->name('journal.edit.categories');
        Route::get('entry/{journal_entry}', [JournalController::class, 'editEntry'])->name('journal.edit.entry');
    });

    // Update entry
    Route::post('update/entry/{journal_entry}', [JournalController::class, 'updateEntry'])->name('journal.update.entry');

    // Delete routes
    Route::prefix('destory')->group(function(){
        Route::post('category/{category}', [JournalController::class, 'destroyCategory'])->name('journal.destroy.category');
        Route::post('destroy/entry/{journal_entry}', [JournalController::class, 'destroyEntry'])->name('journal.destroy.entry');
    });
});

// Goals
Route::prefix('goals')->group(function(){
    // Types route
    Route::get('types', [GoalController::class, 'types'])->name('goals.types');

    // Shift dates route
    Route::post('shift-dates/{goal}', [GoalController::class, 'shiftDates'])->name('goals.shift-dates');

    // Remove parent/convert to sub goal
    Route::post('remove-parent/{goal}', [GoalController::class, 'removeParent'])->name('goals.remove-parent');
    Route::get('convert-sub/{goal}', [GoalController::class, 'convertSubForm'])->name('goals.convert-sub.form');
    Route::post('convert-sub/{goal}', [GoalController::class, 'convertSubSubmit'])->name('goals.convert-sub.submit');

    // Transfer ad hoc items
    Route::get('transfer-ad-hoc-items/{goal}', [GoalController::class, 'transferAdHocItemsForm'])->name('goals.transfer-ad-hoc-items.form');
    Route::post('transfer-ad-hoc-items/{goal}', [GoalController::class, 'transferAdHocItemsSubmit'])->name('goals.transfer-ad-hoc-items.submit');

    // Ad Hoc Deadlines
    Route::prefix('ad-hoc-deadline')->group(function(){
        Route::post('set/{action_item}', [GoalController::class, 'setAdHocDeadline'])->name('goals.ad-hoc-deadline.set');
        Route::post('clear/{action_item}', [GoalController::class, 'clearAdHocDeadline'])->name('goals.ad-hoc-deadline.clear');
    });

    // Bucketlist Deadline
    Route::prefix('bucketlist-deadline')->group(function(){
        Route::post('set/{bucketlist_item}/{goal}', [GoalController::class, 'setBucketlistDeadline'])->name('goals.bucketlist-deadline.set');
        Route::post('clear/{bucketlist_item}', [GoalController::class, 'clearBucketlistDeadline'])->name('goals.bucketlist-deadline.clear');
    });
    
    // Toggle Completed routes
    Route::prefix('toggle-achieved')->group(function(){
        Route::post('goal/{goal}', [GoalController::class, 'toggleAchievedGoal'])->name('goals.toggle-achieved.goal');
        Route::post('action-item/{action_item}', [GoalController::class, 'toggleAchievedActionItem'])->name('goals.toggle-achieved.action-item');
        Route::post('bucketlist-item/{bucketlist_item}', [GoalController::class, 'toggleAchievedBucketlistItem'])->name('goals.toggle-achieved.bucketlist-item');
    });

    // View routes
    Route::prefix('view')->group(function(){
        Route::get('goal/{goal}', [GoalController::class, 'viewGoal'])->name('goals.view.goal');
        Route::get('action-item/{action_item}', [GoalController::class, 'viewActionItem'])->name('goals.view.action-item');
        Route::get('bucketlist-item/{bucketlist_item}/{goal?}', [GoalController::class, 'viewBucketlistItem'])->name('goals.view.bucketlist-item');
    });

    // Create routes
    Route::prefix('create')->group(function(){
        Route::get('goal', [GoalController::class, 'createGoal'])->name('goals.create.goal');
        Route::get('action-item/{goal}', [GoalController::class, 'createActionItem'])->name('goals.create.action-item');
    });

    // Store routes
    Route::prefix('store')->group(function(){
        Route::post('goal', [GoalController::class, 'storeGoal'])->name('goals.store.goal');
        Route::post('action-item/{goal}', [GoalController::class, 'storeActionItem'])->name('goals.store.action-item');
        Route::post('category', [GoalController::class, 'storeCategory'])->name('goals.store.category');
        Route::post('reminder/{action_item}', [GoalController::class, 'storeReminder'])->name('goals.store.reminder');
    });
    
    // Edit routes
    Route::prefix('edit')->group(function(){
        Route::get('goal/{goal}', [GoalController::class, 'editGoal'])->name('goals.edit.goal');
        Route::get('action-item/{action_item}', [GoalController::class, 'editActionItem'])->name('goals.edit.action-item');
        Route::get('categories', [GoalController::class, 'editCategories'])->name('goals.edit.categories');
        Route::get('reminders/{action_item}', [GoalController::class, 'editReminders'])->name('goals.edit.reminders');
    });

    // Update routes
    Route::prefix('update')->group(function(){
        Route::post('goal/{goal}', [GoalController::class, 'updateGoal'])->name('goals.update.goal');
        Route::post('action-item/{action_item}', [GoalController::class, 'updateActionItem'])->name('goals.update.action-item');
        Route::post('manual-progress/{goal}', [GoalController::class, 'updateManualProgress'])->name('goals.update.manual-progress');
    });

    // Destroy routes
    Route::prefix('destroy')->group(function(){
        Route::post('goal/{goal}', [GoalController::class, 'destroyGoal'])->name('goals.destroy.goal');
        Route::post('action-item/{action_item}', [GoalController::class, 'destroyActionItem'])->name('goals.destroy.action-item');
        Route::post('category/{category}', [GoalController::class, 'destroyCategory'])->name('goals.destroy.category');
        Route::post('reminder/{reminder}', [GoalController::class, 'destroyReminder'])->name('goals.destroy.reminder');
    });

    // Root -- at the end of the prefix so scope/category don't block other routes
    Route::get('/{scope?}/{category?}', [GoalController::class, 'index'])->name('goals');
});

// Habits
Route::prefix('habits')->group(function(){
    // Root
    Route::get('/', [HabitsController::class, 'index'])->name('habits');

app/Models/Goal/GoalActionItemReminder.php
<?php

namespace App\Models\Goal;

use Illuminate\Database\Eloquent\Model;
use JamesMills\Uuid\HasUuidTrait;
use Carbon\Carbon;

// Models
use App\Models\Goal\GoalActionItem;

class GoalActionItemReminder extends Model
{
    use HasUuidTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'action_item_id', 'remind_at',
    ];

    /**
     * Get formatted version of a goal action item remind at
     *
     * @param  string  $value
     * @return string
     */
    public function getRemindAtFormattedAttribute()
    {
        $timezone = \Auth::user()->timezone ?? 'America/Denver';
        $carbon = Carbon::parse($this->remind_at)->setTimezone('UTC')->setTimezone($timezone);

        return $carbon->format('D, M j @ g:i A');
    }

    // Action item relationship
    public function actionItem()
    {
        return $this->hasOne(GoalActionItem::class, 'id', 'action_item_id');
    }
}

app/Models/Goal/GoalCategory.php
<?php

namespace App\Models\Goal;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use JamesMills\Uuid\HasUuidTrait;

class GoalCategory extends Model
{
    use HasFactory, HasUuidTrait, SoftDeletes;

    public $timestamps = false;

    protected $fillable = [
        'name', 'user_id',
    ];
}

app/View/Components/Goals/ActionItem.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;
use Carbon\Carbon;

class ActionItem extends Component
{
    // For holding the action item
    public $action_item;

    // For holding formatted deadline
    public $deadline;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($item)
    {
        $this->action_item = $item;

        $this->deadline = Carbon::parse($item->deadline)->format('n/j/y');
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.action-item');
    }
}

app/View/Components/Goals/ActionItemForm.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

// Constants
use App\Helpers\Constants\Goal\Type;

class ActionItemForm extends Component
{
    // To hold the action item we're editing
    public $action_item;

    // For holding the goal the action item is for
    public $goal;

    // For holding goal type constant class
    public $goal_type;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($item = null, $goal = null)
    {
        $this->action_item = $item;

        if(!is_null($goal))
        {
            $this->goal = $goal;
        }
        else
        {
            $this->goal = $item->goal;
        }

        $this->goal_type = Type::class;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.action-item-form');
    }
}

app/View/Components/Goals/ActionItemNav.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

class ActionItemNav extends Component
{
    // And array of which goal action item menu options to show
    public $show;

    // Action item to use when showing action item related nav items, edit/delete/etc
    public $action_item;

    // For holding the goal if the action item hasn't been created
    public $goal;

    // For the selected dropdown redirect param
    public $selected_dropdown;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($show, $item = null, $goal = null)
    {
        $this->show = explode('|', $show);
        $this->action_item = $item;

        if(!is_null($goal))
        {
            $this->goal = $goal;
        }
        else
        {
            $this->goal = $item->goal;
        }

        if(!is_null($item) && in_array('back-goal', $this->show))
        {
            if(is_null($item->deadline))
            {
                $this->selected_dropdown = 'ad-hoc-list';
            }
            else
            {
                $this->selected_dropdown = 'action-plan';
            }
        }
        else
        {
            $this->selected_dropdown = 'details';
        }
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.action-item-nav');
    }
}

app/View/Components/Goals/AdHocDeadlinePopup.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

class AdHocDeadlinePopup extends Component
{
    // For the action item we're creating a deadline dialog for
    public $ad_hoc_item;
    
    // To determine redirect
    public $view_details;

    // To hold the goal we're assigning bucketlist items to
    public $goal;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($item, $details = false, $goal = null)
    {
        $this->goal = $goal;
        $this->ad_hoc_item = $item;
        $this->view_details = (bool) $details;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.ad-hoc-deadline-popup');
    }
}

app/View/Components/Goals/AdHocListItem.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

class AdHocListItem extends Component
{
    // Holds ad hoc action item
    public $ad_hoc_item;

    // Holds the goal for bucketlist ad hoc items
    public $goal;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($item, $goal = null)
    {
        $this->goal = $goal;
        $this->ad_hoc_item = $item;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.ad-hoc-list-item');
    }
}

app/View/Components/Goals/Category.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

class Category extends Component
{
    // Holds category object
    public $category;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($category = null)
    {
        $this->category = $category;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.category');
    }
}

app/View/Components/Goals/EmptyActionItem.php
<?php

namespace App\View\Components\Goals;

use Illuminate\View\Component;

class EmptyActionItem extends Component
{
    // For holding the goal we're creating an action item for
    public $goal;

    // For holding route for links
    public $route;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($goal, $route = 'goals.create.action-item')
    {
        $this->goal = $goal;
        $this->route = $route;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.goals.empty-action-item');
    }
}

resources/views/goals/action-item-details.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.action-item-nav :show="$show" :item="$action_item" />

    <div class="app-container action-item-details">
        {{-- Action item goal --}}
        <p class="goal-name">{{ $action_item->goal->name }}</p>

        {{-- Action item name --}}
        <h2>{{ $action_item->name }}</h2>

        {{-- Deadline --}}
        @if($action_item->achieved)
            <p class="deadline">Achieved On {{ \Carbon\Carbon::parse($action_item->updated_at)->setTimezone(\Auth::user()->timezone ?? 'America/Denver')->format('n/j/y') }}</p>
        @else
            @if(!is_null($action_item->deadline))
                <p class="deadline">Due: {{ \Carbon\Carbon::parse($action_item->deadline)->format('n/j/y') }}</p>
            @else
                <p class="deadline"> <a class="deadline" id="set-deadline-link-{{ $action_item->uuid }}" href="#">Set Deadline</a></p>
                @if($action_item instanceof \App\Models\Bucketlist\BucketlistItem)
                    @push('scripts')
                        <x-goals.ad-hoc-deadline-popup :item="$action_item" :goal="$action_item->goal" />
                    @endpush
                @else
                    @push('scripts')
                        <x-goals.ad-hoc-deadline-popup :item="$action_item" />
                    @endpush
                @endif
            @endif
        @endif

        {{-- Notes --}}
        <h3 class="notes">Notes</h3>
        @if(!is_null($action_item->notes))
            @foreach(explode(PHP_EOL, $action_item->notes) as $line)
                <p class="notes">{{ $line }}</p>
            @endforeach
        @else
            <p class="notes">No notes for this action item!</p>
        @endif

        {{-- Reminders --}}
        @if(count($action_item->reminders) > 0)
            <br/><br/>
            <div class="reminders-container">
                <h3>Reminders</h3>
                <ol>
                    @foreach($action_item->reminders as $reminder)
                        <li>{{ $reminder->remind_at_formatted }}</li>
                    @endforeach
                <ol>
            </div><br/><br/>
        @endif
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/ad-hoc-selector.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back-goal" :goal="$goal" />

    <div class="app-container">
        <form class="create-selector" action="{{ route('goals.transfer-ad-hoc-items.submit', ['goal' => $goal->uuid]) }}" method="POST">
            @csrf
            
            <h2>Transfer Ad-Hoc Items to New Goal</h2>

            <select name="ad-hoc-goal">
                @foreach($ad_hoc_goals as $ad_hoc_goal)
                    <option value="{{ $ad_hoc_goal->uuid }}">{{ $ad_hoc_goal->name }}</option>
                @endforeach
            </select>

            <button type="submit">Done</button>
        </form>
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/categories.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back|create" />

    <div class="app-container categories-list">
        <h2>Edit Categories</h2>
        
        @foreach($categories as $category)
            <x-goals.category :category="$category" />
        @endforeach

        {{-- Add form --}}
        <x-goals.category />

        {{-- Errors --}}
        @error('name')
            @push('scripts')
                <script>
                    sweetAlert('Error', 'error', '#d12828', '{{ $message }}');
                </script>
            @endpush
        @enderror
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/create-action-item.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.action-item-nav show="back-goal" :goal="$goal" />

    <div class="app-container">
        <x-goals.action-item-form :goal="$goal" />
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/create-selector.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back|categories|types" />

    <div class="app-container">
        <form class="create-selector" action="{{ route('goals.create.goal') }}" method="GET">
            
            {{-- Hidden fields --}}
            @isset($future_goal_uuid)
                <input type="hidden" name="future-goal" value="{{ $future_goal_uuid }}" />
            @endisset

            @isset($parent_goal_uuid)
                <input type="hidden" name="parent-goal" value="{{ $parent_goal_uuid }}" />
            @endisset

            <h2>Select a Goal Type</h2>

            <select id="goal-create-type-select" name="type">
                @foreach($goal_types as $goal_type)
                    @if(is_null($future_goal_uuid) || $goal_type->id != $type::FUTURE_GOAL)
                        <option value="{{ $goal_type->id }}">{{ $goal_type->name }}</option>
                    @endif
                @endforeach
            </select>

            @foreach($goal_types as $goal_type)
                <p id="goal-create-type-description-{{ $goal_type->id }}" class="goal-create-type-description">{{ $goal_type->desc }}</p>
            @endforeach

            <button type="submit">Next</button>
        </form>
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/create.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back|create|categories|types" />

    <div class="app-container">
        <x-goals.form :type="$type_id" :future="$future_goal_uuid" :parent="$parent_goal_uuid" />
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/edit-action-item.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.action-item-nav show="back-goal|back-item" :item="$action_item" />

    <div class="app-container">
        <x-goals.action-item-form :item="$action_item" />
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/edit.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back-goal|create|categories|types" :goal="$goal" />

    <div class="app-container">
        <x-goals.form :goal="$goal" />
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/index.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="create|categories|types" />

    <div class="app-container">
        <div class="selector">
            <span>
                Show
                <select class="goal-selector" id="scope-selector">
                    @foreach ($scopes as $scope)
                        <option value="{{ $scope }}" @if($scope == $selected_scope) selected @endif>{{ ucwords($scope) }}</option>
                    @endforeach
                </select>
            </span>
            <span>
                Goals In 
                <select class="goal-selector" id="category-selector">
                    <option value="all">All Categories</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->uuid }}" @if(!is_null($selected_category) && $category->id == $selected_category->id) selected @endif>{{ $category->name }}</option>
                    @endforeach
                </select>
            </span>
        </div>

        @if($goals->count() == 0)
            @isset($selected_scope)
                <x-goals.empty-goal :scope="$selected_scope" />
            @else
                <x-goals.empty-goal />
            @endif
        @else
            @foreach($goals as $goal)
                @if($goals->count() < 3)
                    <x-goals.goal :goal="$goal" class="align-start" />
                @else
                    <x-goals.goal :goal="$goal" />
                @endif
            @endforeach
        @endif
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/parent-selector.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back-goal" :goal="$goal" />

    <div class="app-container">
        <form class="create-selector" action="{{ route('goals.convert-sub.submit', ['goal' => $goal->uuid]) }}" method="POST">
            @csrf
            
            <h2>Assign To Parent Goal</h2>

            <select name="parent-goal">
                @foreach($parent_goals as $parent_goal)
                    <option value="{{ $parent_goal->uuid }}">{{ $parent_goal->name }}</option>
                @endforeach
            </select>

            <button type="submit">Done</button>
        </form>
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/reminders.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.action-item-nav show="back-item" :item="$action_item" />

    <div class="app-container reminders-list">
        <h2>Edit Reminders</h2>
        
        @foreach($action_item->reminders as $reminder)
            <x-goals.reminder :reminder="$reminder" />
        @endforeach

        {{-- Add form --}}
        <x-goals.reminder :item="$action_item" />

        {{-- Errors --}}
        @error('date')
            @push('scripts')
                <script>
                    sweetAlert('Error', 'error', '#d12828', '{{ $message }}');
                </script>
            @endpush
        @enderror

        @error('time')
            @push('scripts')
                <script>
                    sweetAlert('Error', 'error', '#d12828', '{{ $message }}');
                </script>
            @endpush
        @enderror
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection

resources/views/goals/types.blade.php
@extends('layouts.app')

@section('template')
    {{-- Header --}}
    <x-app.header title="Goals" />

    {{-- Side Nav --}}
    <x-goals.nav show="back|create|categories" />

    <div class="app-container">
        @foreach(config('goals.types') as $goal_type)
            <div class="goal-type-container">
                <h2>{{ $goal_type['name'] }}</h2>
                <p>{{ $goal_type['desc'] }}</p>
            </div>
        @endforeach
    </div>

    {{-- Navigation Footer --}}
    <x-app.footer highlight="goals" />
@endsection